server:
  port: 8703
  forward-headers-strategy: framework
  servlet:
    context_path: /viewer/api/v1
  error:
    include-message: always
    include-exception: false
    include-binding-errors: never
    include-stacktrace: never

spring:
  application:
    name: user-security-service
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true



